ALTER TABLE documents
ADD COLUMN IF NOT EXISTS document_id UUID;

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS filename TEXT;

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS chunk_index INTEGER;

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS metadata JSONB;